In [1]:
''' 
 Author: Yoonhyuck WOO / JBNU_Industrial Information system Engineering
 Date; 12. 29. 2020 - 1. 8. 2021
 Title: Artificial Intelligence_Project 2
 Professor: Seung-Hoon Na'''
            
import numpy as np
import random
import matplotlib.pyplot as plt

# 1.1 - numpy.dot

In [4]:
a=[[1,2],[3,4]]
b=[[1,2],[3,4]]

a=np.array(a,dtype='int')
b=np.array(b,dtype='int')

print('example of np.dot')
c=np.dot(a,b)
print(c)

# 1.1 - numpy.einsum
# script부분에서 행,열을 이용하여 transpose, 대각선, 행렬간의 곱세등 선형대수학적인 연산을 가능하게 해줌.
''' ex) np.einsum('ij,jh->ih', a, b) directly specifies the order of the output subscript labelsr
      =>returns matrix multiplication'''
print('\n example of numpy.einsum')
c=[[1,2,3],[4,5,6]]
c=np.array(c)
c=np.einsum('ij->ji',c)
print(c)
#dot과 관련
d=np.einsum('ij,jh->ih',a,b)
print('\n',d)

example of np.dot
[[ 7 10]
 [15 22]]

 example of numpy.einsum
[[1 4]
 [2 5]
 [3 6]]

 [[ 7 10]
 [15 22]]


# 1.2 Numpy: Quiz

67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)<br>
76. Consider a one-dimensional array Z, 
    build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) 
    and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)<br>
77. How to negate a boolean, or to change the sign of a float inplace? (★★★)<br>
85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)<br>
94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

 - #67. Considering a four dimensions array, how to get sum over the last two axis at once?

In [5]:
P_67=np.arange(54).reshape(2,3,3,3)
print(P_67)

print('\nSUM')
print(P_67.sum(axis=(-2,-1)))

[[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]]

  [[ 9 10 11]
   [12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]
   [24 25 26]]]


 [[[27 28 29]
   [30 31 32]
   [33 34 35]]

  [[36 37 38]
   [39 40 41]
   [42 43 44]]

  [[45 46 47]
   [48 49 50]
   [51 52 53]]]]

SUM
[[ 36 117 198]
 [279 360 441]]


- #76<br> Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [15]:
P_76 = np.arange(12).reshape(4,3)
print('before')
print(P_76)

print('after')
print(P_76[::-1,::-1])


before
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
after
[[11 10  9]
 [ 8  7  6]
 [ 5  4  3]
 [ 2  1  0]]


- #77. How to negate a boolean, or to change the sign of a float inplace?

In [8]:
# hint: np.logical_not, np.negative
# negate= FALSE-> True, True -> False
print('before')
diago=[[1,0,0],[0,1,0],[0,0,1]]

dia=np.logical_not(diago)
diag=np.negative(diago)
diag1=np.logical_not(diago)
print(diago)
print(diag1)

print('\nbefore')
k1=1
for i in diag1:
    for j in i:
        print(k1,':',j)
        k1=k1+1


def negate_boolean(x):
    k2=1
    y=np.logical_not(x)
    for i in y:
        for j in i:
            if j==False:
                j=True
            elif j==True: 
                j=False
            print(k2,':',j)
            k2=k2+1
print('\nafter')
negate_boolean(diago)

before
[[1, 0, 0], [0, 1, 0], [0, 0, 1]]
[[False  True  True]
 [ True False  True]
 [ True  True False]]

before
1 : False
2 : True
3 : True
4 : True
5 : False
6 : True
7 : True
8 : True
9 : False

after
1 : True
2 : False
3 : False
4 : False
5 : True
6 : False
7 : False
8 : False
9 : True


 - #85. Create a 2D array subclass such that Z[i,j] == Z[j,i] => diagonal array

In [10]:
#diagonal=np.arange(9).reshape(3,3)
P_85=[[1,0,0],[0,1,0],[0,0,1]]
P_85=np.array(P_85,dtype='int')
print('before')
print(P_85)

print('after')
P_85=np.einsum('ij->ji',P_85)
print(P_85)

before
[[1 0 0]
 [0 1 0]
 [0 0 1]]
after
[[1 0 0]
 [0 1 0]
 [0 0 1]]


- #94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [13]:
P_94=np.random.random((10,3))*10
P_94=np.array(P_94,dtype='int')
P_94
i=0
for j in P_94:
    if j[0]==j[1]==j[2]:
        continue
    else:
        i=i+1
        print(j)
print('unequal_count',i)

[5 4 4]
[0 4 5]
[9 2 7]
[5 5 3]
[2 7 8]
[5 0 0]
[1 0 0]
[5 7 5]
[9 8 1]
[7 5 3]
unequal_count 10


# 1.3 Nupmy: 선형방정식 풀기

In [12]:
# np.dot(a, a_inv) => 단위행렬(unit matrix) 
#pseudo inverse A+는 다음과 같이 계산된다.=>(A+=A^TA)^-1A^T

np.set_printoptions(precision=2)
a=random.randrange(2,4)
b=random.randrange(2,4)
P_13=np.random.randint(-3,4,(a,b))
P_13
B=np.random.randint(0,10,(a,1))
print('A')
print(P_13)
print('\nB')
print(B)

def linearsol(x,y):
    x_inv=np.linalg.inv(x)
    print('역')
    print(x_inv)
    
    #assert 
    
    unit=np.dot(x_inv,x)
    unit=np.array(unit, dtype='int')
    print('A*역 => 역행렬 잘 구했는지 확인')
    print(unit)
    print('\n해')
    return print(np.dot(x_inv,y))

def leastsquaresol(a,b,x,y):
    if a>b:
        x_tran=np.transpose(x)
        pseudo_inverse=np.dot(np.linalg.inv(np.dot(x_tran,x)),x_tran)
        return print(np.dot(pseudo_inverse,y))
    elif a<b:
        print('Infinite solutions')
    
    
if a==b:
    print('\n result')
    linearsol(P_13,B)
else:
    print('\n result')
    leastsquaresol(a,b,P_13,B)
    

A
[[ 3 -2 -1]
 [-2  0 -1]
 [ 3  3 -3]]

B
[[3]
 [2]
 [1]]

 result
역
[[ 0.09 -0.27  0.06]
 [-0.27 -0.18  0.15]
 [-0.18 -0.45 -0.12]]
A*역 => 역행렬 잘 구했는지 확인
[[1 0 0]
 [0 1 0]
 [0 0 1]]

해
[[-0.21]
 [-1.03]
 [-1.58]]
