In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt
np.set_printoptions(precision=3)

# Make relu class

In [2]:
class relu():
    def __init__(self):
        self.mask = None
        
    def forward(self,x):
        self.mask = (x <=0)
        out = x.copy()
        out[self.mask] = 0
        
        return out
    
    def backward(self, dout):
        dout[self.mask]= 0
        
        dx=dout
        
        return dx

# Make Softmax & cross_entropy class

In [11]:
class SCE():
    def __init__(self):
        self.exp_o=0
        self.exp_sum_exp_o=0
        self.softmax = 0
        self.result = 0
        
        self.o = 0
        self.U = 0
        self.d = 0
        
    def forward(self,X,h,y):
        
        #softmax
        self.d = np.random.randint(-4,4,size=1)
        self.U = np. random.randint(-4,4,(X.shape[0], h.shape[0]))
        self.o = np.dot(self.U, h)+self.d
        
        print('U')
        print(self.U)
        
        print('o')
        print(self.o)
        
        #cross_entropy
        delta = np.max(self.o)
        
        print('delta')
        print(delta)
        self.exp_o = np.exp(self.o-delta)
        self.sum_exp_o = np.sum(self.exp_o)
        
        print('\nexp_o')
        print(self.exp_o)
        
        print('\nsum_exp_o')
        print(self.sum_exp_o)
        
        
        print('\nsoftmax')
        self.softmax = self.exp_o / self.sum_exp_o
        print(self.softmax)
        
        # cross_entropy + 마이너스 무한대가 생기지 않도록 만듦
        self.result= - np.sum(y * np.log(self.softmax))
        print('Loss')
       
        return print(self.result)
        
    def backward(self,y):
        batch_size = y.shape[0]
        dx = (self.softmax-y) / batch_size
        
        return dx

### MLP

In [12]:
class MLP():
    def __int__(self):
        
        self.W = 0  
        self.b = 0
        
        self.U = 0
        self.d = 0
        self.J = 0
        self.h = 0
        
    def forward(self, X, N):
        self.b = np.random.randint(-4,4,size=1)
        self.W = np. random.randint(-4,4,(N,X.shape[0]))
        
        print('X')
        print(X)
        
        print('W')
        print(self.W)
        
        #relu
        a = np.dot(self.W,X) + self.b
        self.h = relu.forward(self,a)
       
        print('output')
        return print(self.h)
    
    def backward(self,X,y):
        dJdU = np.dot(SCE.backward(self,y), np.transpose(self.h))
        dJdd = SCE.backward(self,y)*np.ones_like(SCE.d) 
        dJdh = np.dot(np.transpose(SCE.U), SCE.backward(self,y))
        dJdW = np.dot(relu.backward(self,dJdh), np.transpose(X))
        
        print('dJdU')
        print(dJdU)
        
        print('dJdd')
        print(dJdd)
        
        print('dJdh')
        print(dJdh)
        
        print('dJdW')
        print(dJdW)

# 4.1

In [13]:
model = MLP()
model_2 = SCE()
a = [[1],[2],[3],[5]]
a = np.array(a)
y = [[1],[0],[0],[0]]
y=np.array(y)

model.forward(a,2)
model_2.forward(a,a,y)
#model.backward(a,y)

X
[[1]
 [2]
 [3]
 [5]]
W
[[ 3 -1  0 -2]
 [-4 -3  3 -3]]
output
[[0]
 [0]]
U
[[ 3  3 -4 -2]
 [ 1 -3  1  3]
 [-3 -1  3  0]
 [-1 -1  0  3]]
o
[[-11]
 [ 15]
 [  6]
 [ 14]]
delta
15

exp_o
[[5.109e-12]
 [1.000e+00]
 [1.234e-04]
 [3.679e-01]]

sum_exp_o
1.3680028509806381

softmax
[[3.735e-12]
 [7.310e-01]
 [9.021e-05]
 [2.689e-01]]
Loss
26.31335190324836
