In [145]:
import numpy as np
import random
import matplotlib.pyplot as plt
np.set_printoptions(precision=3)

# Make relu class

In [146]:
class relu():
    def __init__(self):
        self.mask = None
        
    def forward(self,x):
        self.mask = (x <=0)
        out = x.copy()
        out[self.mask] = 0
        
        return out
    
    def backward(self, dout):
        dout[self.mask]= 0
        
        dx=dout
        
        return dx

# Make softmax class

In [117]:
class softmax():
    def __init__(self):
        self.o = 0
        self.U = 0
        self.d = 0
        
    def forward(self, X, h):
        self.d = np.random.randint(-4,4,size=1)
        self.U = np. random.randint(-4,4,(X.shape[0], h.shape[0]))
        self.o = np.dot(self.U, h)+self.d
        
        print('U')
        print(self.U)
        
        print('o')
        print(self.o)
        
        return self.o

# Make Softmax & cross_entropy class

In [158]:
class SCE():
    def __init__(self):
        self.exp_o=0
        self.exp_sum_exp_o=0
        self.softmax = 0
        self.result = 0
        
        self.o = 0
        self.U = 0
        self.d = 0
        
    def forward(self,X,h,y):
        
        #softmax
        self.d = np.random.randint(-4,4,size=1)
        self.U = np. random.randint(-4,4,(X.shape[0], h.shape[0]))
        self.o = np.dot(self.U, h)+self.d
        
        print('U')
        print(self.U)
        
        print('o')
        print(self.o)
        
        #cross_entropy
        delta = np.max(self.o)
        
        print('delta')
        print(delta)
        self.exp_o = np.exp(self.o-delta)
        self.sum_exp_o = np.sum(self.exp_o)
        
        print('exp_o')
        print(self.exp_o)
        
        print('sum_exp_o')
        print(self.sum_exp_o)
        
        
        print('softmax')
        self.softmax = self.exp_o / self.sum_exp_o
        print(self.softmax)
        
        # cross_entropy + 마이너스 무한대가 생기지 않도록 만듦
        self.result= - np.sum(y * np.log(self.softmax))
        print('Loss')
       
        return print(self.result)
        
    def backward(self,y):
        batch_size = y.shape[0]
        dx = (self.softmax-y) / batch_size
        
        return dx

### MLP

In [159]:
class MLP():
    def __int__(self):
        
        self.W = 0  
        self.b = 0
        
        self.U = 0
        self.d = 0
        self.J = 0
        self.h = 0
        
    def forward(self, X, N):
        self.b = np.random.randint(-4,4,size=1)
        self.W = np. random.randint(-4,4,(N,X.shape[0]))
        
        print('X')
        print(X)
        
        print('W')
        print(self.W)
        
        #relu
        a = np.dot(self.W,X) + self.b
        self.h = relu.forward(self,a)
       
        print('output')
        return print(self.h)
    
    def backward(self,X,y):
        dJdU = np.dot(SCE.backward(self,y), np.transpose(self.h))
        dJdd = SCE.backward(self,y)*np.ones_like(SCE.d) 
        dJdh = np.dot(np.transpose(SCE.U), SCE.backward(self,y))
        dJdW = np.dot(relu.backward(self,dJdh), np.transpose(X))
        
        print('dJdU')
        print(dJdU)
        
        print('dJdd')
        print(dJdd)
        
        print('dJdh')
        print(dJdh)
        
        print('dJdW')
        print(dJdW)

In [160]:
'''
# Layer, dimension

layer=[]
L=int(input('Layer: '))
for i in range(L):
    print(i+1,'th Dimenson', end = ' ') 
    d=int(input(':'))
    
    layer.append(d)

    
length = len(layer)
print(length)'''

"\n# Layer, dimension\n\nlayer=[]\nL=int(input('Layer: '))\nfor i in range(L):\n    print(i+1,'th Dimenson', end = ' ') \n    d=int(input(':'))\n    \n    layer.append(d)\n\n    \nlength = len(layer)\nprint(length)"

# 4.2

In [164]:
## Layer, dimension
layer=[]
L=int(input('Layer: '))

for i in range(L):
    print(i+1,'th Dimenson', end = ' ') 
    d=int(input(':'))
    
    layer.append(d)
    
length = len(layer)

model_1 = MLP()
#model_2 = softmax()
model_3 = SCE()

a = [[1],[2],[3],[5]]
a = np.array(a)
y = [[1],[0],[0],[0]]
y=np.array(y)

for i in range(length):
    print('-------------',i+1,'번째 layer-------------')
    if (i == 0):
        x = a
        model_1.forward(np.array(x),layer[i])
        x = model_1.h

    else:
        model_1.forward(np.array(x),layer[i])
        x = model_1.h

print('\n')
print('x')
print(x)

#o = model_2.forward(a,x)
model_3.forward(a,x,y)

Layer:  3


1 th Dimenson 

: 3


2 th Dimenson 

: 2


3 th Dimenson 

: 3


------------- 1 번째 layer-------------
X
[[1]
 [2]
 [3]
 [5]]
W
[[ 1  2  1  3]
 [ 2 -2  0  3]
 [ 1 -4  0 -3]]
output
[[21]
 [11]
 [ 0]]
------------- 2 번째 layer-------------
X
[[21]
 [11]
 [ 0]]
W
[[-1  3 -2]
 [-2 -3 -4]]
output
[[15]
 [ 0]]
------------- 3 번째 layer-------------
X
[[15]
 [ 0]]
W
[[ 0  0]
 [-4  1]
 [-2 -3]]
output
[[3]
 [0]
 [0]]


x
[[3]
 [0]
 [0]]
U
[[ 0 -1 -1]
 [ 1 -4 -2]
 [ 2  3  1]
 [ 3  1  2]]
o
[[0]
 [3]
 [6]
 [9]]
delta
9
exp_o
[[1.234e-04]
 [2.479e-03]
 [4.979e-02]
 [1.000e+00]]
sum_exp_o
1.052389230348617
softmax
[[1.173e-04]
 [2.355e-03]
 [4.731e-02]
 [9.502e-01]]
Loss
9.051063036711472


In [171]:
a=np.array([[1,2],[-1,3],[3,3]])
print(a)
np.maximum(a,0)

[[ 1  2]
 [-1  3]
 [ 3  3]]


array([[1, 2],
       [0, 3],
       [3, 3]])