In [1]:
''' 
 Author: Yoonhyuck WOO / JBNU_Industrial Information system Engineering
 Date; 2. 21. 2021 - 3. 7. 2021
 Title: Artificial Intelligence_Project 2
 Professor: Seung-Hoon Na'''
  
import numpy as np
import random
import matplotlib.pyplot as plt
np.set_printoptions(precision=3)

# Make relu class

In [14]:
class relu():
    def __init__(self):
        self.mask = None
        
    def forward(self,x):
        self.mask = (x <= 0)
        out = x.copy()
        out[self.mask] = 0
        
        return out
    
    def backward(self,affine, dout):
        mask = (affine<=0)
        dout[mask]= 0
        
        dx = dout
        
        return dx

### MLP

In [6]:
class MLP():
    def __init__(self):
        self.b = np.random.randint(-4,4,size=1)
        self.a = 0
        
    def forward(self,W, X, N):
        #self.W = np. random.randint(-4,4,(N,X.shape[0]))
        
        print('X')
        print(X)
        
        print('W')
        print(W)
        
        print('next_X')
        #relu
        self.a = np.dot(W,X) + self.b
        
        return self.a

# Make softmax class

In [7]:
class softmax():    
    def __init__(self):
        self.r = 0
        self.d = np.random.randint(-4,4,size=1)
        
    def forward(self,X,h,U):
        self.r = np.dot(U, h)+self.d

        print('R')
        print(self.r)

        delta = np.max(self.r)
        
        print('delta')
        print(delta)
        self.exp_o = np.exp(self.r-delta)
        self.sum_exp_o = np.sum(self.exp_o)
        
        print('\nexp_o')
        print(self.exp_o)
        
        print('\nsum_exp_o')
        print(self.sum_exp_o)
        
        print('\nsoftmax')
        self.softmax = self.exp_o / self.sum_exp_o
        
        return self.softmax

# Make Cross_entropy class

In [8]:
class CE():
    def __init__(self):
        self.result = 0
        
    def forward(self, y, softMAX):
        # cross_entropy + 마이너스 무한대가 생기지 않도록 만듦
        self.result = - np.sum(y * np.log(softMAX))
        print('Loss')
       
        return self.result
        
    def backward(self, y, softMAX):
        batch_size = y.shape[0]
        dJdR = (softMAX-y) / batch_size
        
        print('dx')
        print(dJdR)
        
        return dJdR

# 4.2

In [19]:
# Layer, dimension
model = MLP()
ce = CE()
Relu = relu()
SOFTMAX = softmax()

layer=[]
param_w = []
param_b = []
affine = []

grad_w = []
grad_b = []
grad_affine = []


L = int(input('Layer: '))

for i in range(L):
    print(i+1,'th Dimenson', end = ' ') 
    d=int(input(':'))
    
    layer.append(d)
    
length = len(layer)

X = [[1],[3],[3],[7]]
X = np.array(X)
y = [[1],[0],[0],[0]]
y=np.array(y)

for i in range(length):
    print('-------------',i+1,'번째 layer-------------')
    if (i == 0):
        x = X
        W = np. random.randint(-4,4,(layer[i],np.array(x).shape[0]))
        a = model.forward(W, np.array(x),layer[i])
        print(a)
        
        x = Relu.forward(a)
        param_w.append(W)
        affine.append(a)
    else:
        W = np. random.randint(-4,4,(layer[i],np.array(x).shape[0]))
        a = model.forward(W, np.array(x),layer[i])
        Relu.forward(a)
        print(a)
        
        param_w.append(W)
        affine.append(a)
        x = Relu.forward(a)

print('\n')
print('x')
print(x)

'''
print('\n')
print('param_W')
print(param_w)
'''
print('\n')
print('affine')
print(affine)

print('U')
U = np. random.randint(-4,4,(X.shape[0], x.shape[0]))
print(U)

o = SOFTMAX.forward(X,x,U) # softmax
print(o)

print('J')
J = ce.forward(y, o) # cross_Entropy
print(J)

############# BACKWARD #############
dJdR = ce.backward(y,o) #softmax & cross_Entropy loss
dJdh = np.dot(np.transpose(U), dJdR)
dJdU = np.dot(dJdR,np.transpose(x))
dJda = Relu.backward(affine[2],dJdh)

print('dJdR')
print(dJdR)

print('dJdU')
print(dJdU)


print('dJdh')
print(dJdh)

print('dJda')
print(dJda)
param_w.reverse()
affine.reverse()

affine.append(X)
for x in range(length):
    print('------------- from back',x+1,'번째 backpropagation-------------')
    if (x == 0):
        
        dJd_ = dJda
        print('dJd_')
        print(dJd_)
        
        print('affine')
        print(affine[x+1])

    else :
        
        print('np.transpose(param_w)')
        print(np.transpose(param_w[x-1]))

        dJd_ = np.dot(np.transpose(param_w[x-1]),dJd_)
        print('dJd_')
        print(dJd_)
        
        print('affine')
        print(affine[x+1])
        
        print('Relu')
        print(Relu.backward(affine[x],dJd_))
    dJdw = np.dot(dJd_, np.transpose(affine[x+1]))
    dJdb = np.dot(dJd_, np.ones_like(model.b))
        
    print('dJdw')
    print(dJdw)
    grad_w.append(dJdw)
    grad_b.append(dJdb)
    #grad_affine.append()
    
#print('grad_w')
#print(grad_w)

Layer:  3


1 th Dimenson 

: 3


2 th Dimenson 

: 2


3 th Dimenson 

: 3


------------- 1 번째 layer-------------
X
[[1]
 [3]
 [3]
 [7]]
W
[[-3  1  0  2]
 [ 0  2  1  2]
 [ 1  3  2  3]]
next_X
[[17]
 [26]
 [40]]
------------- 2 번째 layer-------------
X
[[17]
 [26]
 [40]]
W
[[ 1  0 -3]
 [ 3 -1  3]]
next_X
[[-100]
 [ 148]]
------------- 3 번째 layer-------------
X
[[  0]
 [148]]
W
[[ 2  0]
 [ 0  1]
 [-3  0]]
next_X
[[  3]
 [151]
 [  3]]


x
[[  3]
 [151]
 [  3]]


affine
[array([[17],
       [26],
       [40]]), array([[-100],
       [ 148]]), array([[  3],
       [151],
       [  3]])]
U
[[-3 -1 -1]
 [-4  1  1]
 [ 0  0  1]
 [ 1  2  1]]
R
[[-160]
 [ 145]
 [   6]
 [ 311]]
delta
311

exp_o
[[2.801e-205]
 [8.075e-073]
 [3.469e-133]
 [1.000e+000]]

sum_exp_o
1.0

softmax
[[2.801e-205]
 [8.075e-073]
 [3.469e-133]
 [1.000e+000]]
J
Loss
471.0
dx
[[-2.500e-001]
 [ 2.019e-073]
 [ 8.672e-134]
 [ 2.500e-001]]
dJdR
[[-2.500e-001]
 [ 2.019e-073]
 [ 8.672e-134]
 [ 2.500e-001]]
dJdU
[[-7.500e-001 -3.775e+001 -7.500e-001]
 [ 6.056e-073  3.048e-071  6.056e-073]
 [ 2.602e-133  1.309e