In [18]:
import numpy as np
import random
import matplotlib.pyplot as plt
np.set_printoptions(precision=3)

In [164]:
#relu랑 softmax 함수로 만들기
class relu():
    def __init__(self):
        self.mask = None
        
    def forward(self,x):
        self.mask = (x <=0)
        out = x. copy()
        out[self.mask] = 0
        
        return out
    
    def backward(self, dout):
        dout[self.mask]= 0
        
        dx=dout
        
        return dx

In [165]:
class softmax_with_loss():
    def __init__(self):
        self.exp_o=0
        self.exp_sum_exp_o=0
        self.softmax = 0
        self.result = 0
        
    def forward(self,o):
        delta = np.max(o)
        self.exp_o=np.exp(o-delta)
        self.sum_exp_o=np.sum(self.exp_o)
        print('softmax')
        self.softmax = self.exp_o / self.sum_exp_o
        print(self.softmax)
        
        # cross_entropy
        # 마이너스 무한대가 생기지 않도록 만듦
        self.result= -np.sum(y*np.log(self.softmax))
        print('Loss')
        print(self.result)
        
        return self.result
        
    def backward(self,y):
        batch_size = y.shape[0]
        dx = (self.softmax-y) / batch_size
        
        return dx


In [168]:
class MLP():
    def __int__(self):
        self.L=0 # 은닉층 수
        self.N=0 # 출력층 뉴런수
        #self.mask=0
        
        self.W = 0  
        self.b = 0
        
        self.U = 0
        self.d = 0
        self.J = 0
        
        self.h = 0
        
    def forward(self,X,y,L,N):
        self.b = np.random.randint(-4,4,size=1)
        self.W = np. random.randint(-4,4,(N,X.shape[0]))
        
        print('X')
        print(X)
        
        print('self.W')
        print(self.W)
     
        print('self.b')
        print(self.b)
        
        #ReLU
        #self.h = np.maximum((np.dot(self.W,X) + self.b),0)
        a=np.dot(self.W,X) + self.b
        self.h = relu.forward(self,a)
         
        print('a')
        print(a)
        
        print('self.h')
        print(self.h)
        
        #softmax
        self.U = np. random.randint(-4,4,(y.shape[0],self.h.shape[0]))
        self.d = np.random.randint(-4,4,size=1)
        
        print('self.U')
        print(self.U)
        
        o = np.dot(self.U,self.h)+self.d
        print('o')
        print(o)
        softmax.forward(self,o)
       
    def backward(self,X,y,L,N):
        dJdU = np.dot(softmax_with_loss.backward(self,y), np.transpose(self.h))
        dJdd = softmax_with_loss.backward(self,y)*np.ones_like(self.d) 
        
        dJdh = np.dot(np.transpose(self.U), softmax_with_loss.backward(self,y))
        
        print('dJdh')
        print(dJdh)
        dJdw = np.dot(relu.backward(self,dJdh), np.transpose(X))
      
        
        print('dJdw')
        print(dJdw)
        
        print('dJdD')
        print(dJdd)
        
        print('dJdU')
        print(dJdU)

In [173]:
model = MLP()
a = [[1],[2],[3],[5]]
a = np.array(a)
y = [[1],[0],[0],[0]]
y=np.array(y)
model.forward(a,y,1,2)
model.backward(a,y,1,2)

X
[[1]
 [2]
 [3]
 [5]]
self.W
[[-4 -4  3 -1]
 [-2  2  2  3]]
self.b
[-1]
a
[[-9]
 [22]]
self.h
[[ 0]
 [22]]
self.U
[[ 0  2]
 [ 2  1]
 [ 0 -2]
 [-3 -4]]
o
[[ 43]
 [ 21]
 [-45]
 [-89]]
softmax
[[1.000e+00]
 [2.789e-10]
 [6.055e-39]
 [4.711e-58]]
dJdh
[[ 1.395e-10]
 [-6.974e-11]]
dJdw
[[ 0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [-6.974e-11 -1.395e-10 -2.092e-10 -3.487e-10]]
dJdD
[[-6.974e-11]
 [ 6.974e-11]
 [ 1.514e-39]
 [ 1.178e-58]]
dJdU
[[-0.000e+00 -1.534e-09]
 [ 0.000e+00  1.534e-09]
 [ 0.000e+00  3.330e-38]
 [ 0.000e+00  2.591e-57]]


In [171]:
a=np.array([[1,2],[-1,3],[3,3]])
print(a)
np.maximum(a,0)

[[ 1  2]
 [-1  3]
 [ 3  3]]


array([[1, 2],
       [0, 3],
       [3, 3]])