In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt
np.set_printoptions(precision=3)

In [2]:
#relu랑 softmax 함수로 만들기
class relu():
    def __init__(self):
        self.mask = None
        
    def forward(self,x):
        self.mask = (x <=0)
        out = x.copy()
        out[self.mask] = 0
        
        return out
    
    def backward(self, dout):
        dout[self.mask]= 0
        
        dx=dout
        
        return dx

In [39]:
class MLP():
    def __int__(self): 
        self.W = 0  
        self.b = 0
        
        self.U = 0
        self.d = 0
        self.J = 0
        self.h = 0
        
    def forward(self, X, N):
        self.b = np.random.randint(-4,4,size=1)
        self.W = np. random.randint(-4,4,(N,X.shape[0]))
        
        print('X')
        print(X)
        
        print('W')
        print(self.W)
        
        #relu
        a = np.dot(self.W,X) + self.b
        self.h = relu.forward(self,a)
       
        print('output')
        return print(self.h)
    
    def backward(self,X,y):
        dJdU = np.dot(cross_entropy.backward(self,y), np.transpose(self.h))
        dJdd = cross_entropy.backward(self,y)*np.ones_like(cross_entropy.d) 
        dJdh = np.dot(np.transpose(cross_entropy.U), cross_entropy.backward(self,y)
        dJdw = np.dot(relu.backward(self,dJdh), np.transpose(X))

In [3]:
class softmax():
    def __init__(self):
        self.o = 0
    def forward(self, U, h, d):
        self.o = np.dot(U,h)+d
        
        return self.o

In [40]:
'''
# Layer, dimension

layer=[]
L=int(input('Layer: '))
for i in range(L):
    print(i+1,'th Dimenson', end = ' ') 
    d=int(input(':'))
    
    layer.append(d)

    
length = len(layer)
print(length)'''

"\n# Layer, dimension\n\nlayer=[]\nL=int(input('Layer: '))\nfor i in range(L):\n    print(i+1,'th Dimenson', end = ' ') \n    d=int(input(':'))\n    \n    layer.append(d)\n\n    \nlength = len(layer)\nprint(length)"

In [41]:
# 4.1
model = MLP()
a = [[1],[2],[3],[5]]
a = np.array(a)
y = [[1],[0],[0],[0]]
y=np.array(y)

model.forward(a,2)
#model.backward(a,y)

X
[[1]
 [2]
 [3]
 [5]]
W
[[ 3  0  3 -2]
 [ 0  3 -2  1]]
output
[[4]
 [7]]


In [46]:
### 4.2

# Layer, dimension
layer=[]
L=int(input('Layer: '))

for i in range(L):
    print(i+1,'th Dimenson', end = ' ') 
    d=int(input(':'))
    
    layer.append(d)
    
length = len(layer)

model = MLP()
a = [[1],[2],[3],[5]]
a = np.array(a)
y = [[1],[0],[0],[0]]
y=np.array(y)

for i in range(length):
    print('-------------',i+1,'번째 layer-------------')
    if (i == 0):
        x = a
        model.forward(np.array(x),layer[i])
        x = model.h

    else:
        model.forward(np.array(x),layer[i])
        x = model.h

print('\n')
cross_entropy.forward(y,x)

Layer:  3


1 th Dimenson 

: 3


2 th Dimenson 

: 2


3 th Dimenson 

: 3


------------- 1 번째 layer-------------
X
[[1]
 [2]
 [3]
 [5]]
W
[[-1 -2  0  1]
 [ 1 -4 -1  1]
 [ 3  0 -2 -3]]
output
[[0]
 [0]
 [0]]
------------- 2 번째 layer-------------
X
[[0]
 [0]
 [0]]
W
[[ 3 -2 -4]
 [ 3 -3 -4]]
output
[[0]
 [0]]
------------- 3 번째 layer-------------
X
[[0]
 [0]]
W
[[ 0  0]
 [ 0 -4]
 [ 2  1]]
output
[[0]
 [0]
 [0]]




NameError: name 'U' is not defined

In [171]:
a=np.array([[1,2],[-1,3],[3,3]])
print(a)
np.maximum(a,0)

[[ 1  2]
 [-1  3]
 [ 3  3]]


array([[1, 2],
       [0, 3],
       [3, 3]])