In [59]:
import numpy as np
import random
import matplotlib.pyplot as plt

In [108]:
class MLP():
    def __int__(self):
        self.L=0 # 은닉층 수
        self.N=0 # 출력층 뉴런수
        
        self.W = 0  
        self.b = 0
        
        self.U = 0
        self.d = 0
        self.J = 0
        
        self.exp_o=0
        self.exp_sum_exp_o=0
        
        self.h = 0
        self.softmax = 0
    
    def forward(self,X,y,L,N):
        self.b = np.random.uniform(-1,1,size=1)
        self.d = np.random.uniform(-1,1,size=1)
        
        self.W = np. random.randint(-1,1,(X.shape[1],N))
        self.U = np. random.randint(-1,1,(N,1))
        
        print('self.W')
        print(self.W)
        print('self.U')
        print(self.U)
        
        print('self.b')
        print(self.b)
        
        print('self.d')
        print(self.d)
        
        #ReLU
        self.h = np.maximum((np.dot(X,self.W) + self.b),0)
        print('np.dot(X,self.W) + self.b')
        print((np.dot(X,self.W) + self.b))
        print('self.h')
        print(self.h)
        
        #softmax
    
        o=np.dot(self.h,self.U)+self.d
        
        print('self.d')
        print(self.d)
        
        print('self.exp_o')
        self.exp_o=np.exp(o)
        print(self.exp_o)
        print('self.sum_exp_o')
        self.sum_exp_o=np.sum(self.exp_o)
        print(self.sum_exp_o)
        
        self.softmax = self.exp_o / self.sum_exp_o
        print('self.softmax')
        print(self.softmax)
        
        #cross_entropy
        delta = 1e-7 #마이너스 무한대가 생기지 않도록 만듦
        
        result=-np.sum(y*np.log(self.softmax + delta))
        
        def backward(self,X,y,L,N):

In [109]:
model = MLP()
a = [[1,2,3]]
a = np.array(a)
y = [[1]]
y=np.array(y)
model.forward(a,y,1,2)

self.W
[[-1 -1]
 [-1 -1]
 [ 0  0]]
self.U
[[-1]
 [-1]]
self.b
[-0.36329095]
self.d
[-0.68093997]
np.dot(X,self.W) + self.b
[[-3.36329095 -3.36329095]]
self.h
[[0. 0.]]
self.d
[-0.68093997]
self.exp_o
[[0.50614101]]
self.sum_exp_o
0.5061410125552126
self.softmax
[[1.]]


In [10]:
a=np.array([[1,-3],[-1,3],[-3,3]])
print(a)
np.maximum(a,0)

[[ 1 -3]
 [-1  3]
 [-3  3]]


array([[1, 0],
       [0, 3],
       [0, 3]])