In [59]:
import numpy as np
import random
import matplotlib.pyplot as plt

In [ ]:
relu랑 softmax 함수로 만들기

In [174]:
class MLP():
    def __int__(self):
        self.L=0 # 은닉층 수
        self.N=0 # 출력층 뉴런수
        
        self.W = 0  
        self.b = 0
        
        self.U = 0
        self.d = 0
        self.J = 0
        
        self.exp_o=0
        self.exp_sum_exp_o=0
        
        self.h = 0
        self.softmax = 0
    
    def forward(self,X,y,L,N):
        self.b = np.random.randint(-1,3,size=1)
        self.d = np.random.randint(-1,3,size=1)
        
        self.W = np. random.randint(-4,4,(N,X.shape[0]))
        
        
        print('X')
        print(X)
        
        print('self.W')
        print(self.W)
     
        print('self.b')
        print(self.b)
        
        print('self.d')
        print(self.d)
        
        #ReLU
        self.h = np.maximum((np.dot(self.W,X) + self.b),0)
        
        print('np.dot(X,self.W) + self.b')
        print((np.dot(self.W,X) + self.b))
        print('self.h')
        print(self.h)
        
        #softmax
        self.U = np. random.randint(-4,4,(N,self.h.shape[0]))
        print('self.U')
        print(self.U)
        
        o=np.dot(self.U,self.h)+self.d
        delta = np.max(o)
        
        print('d')
        print(self.d)
        
        print('o')
        print(o)
        
        print('exp_o')
        self.exp_o=np.exp(o-delta)
        
        print(self.exp_o)
        print('sum_exp_o')
        
        self.sum_exp_o=np.sum(self.exp_o)
        print(self.sum_exp_o)
        
        self.softmax = self.exp_o / self.sum_exp_o
        
        print('softmax')
        print(self.softmax)
        
        #cross_entropy
         #마이너스 무한대가 생기지 않도록 만듦
        
        result= -np.sum(y*np.log(self.softmax))
        print('Loss')
        print(result)
        
       # def backward(self,X,y,L,N):

In [175]:
model = MLP()
a = [[1],[2],[3],[5]]
a = np.array(a)
y = [[1],[0],[0],[0]]
y=np.array(y)
model.forward(a,np.transpose(y),1,2)

X
[[1]
 [2]
 [3]
 [5]]
self.W
[[-3 -4  3  1]
 [ 1 -2  0  1]]
self.b
[0]
self.d
[0]
np.dot(X,self.W) + self.b
[[3]
 [2]]
self.h
[[3]
 [2]]
self.U
[[-1 -1]
 [ 3  3]]
d
[0]
o
[[-5]
 [15]]
exp_o
[[2.06115362e-09]
 [1.00000000e+00]]
sum_exp_o
1.0000000020611537
softmax
[[2.06115362e-09]
 [9.99999998e-01]]
Loss
20.000000004122306


In [131]:
a=np.array([[1,2],[-1,3],[3,3]])
print(a)
np.maximum(a,0)

[[ 1 -3]
 [-1  3]
 [-3  3]]


array([[1, 0],
       [0, 3],
       [0, 3]])